version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LOG_CLEANUP_POLICY: "compact"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 60000
      KAFKA_LOG_SEGMENT_BYTES: 1000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
    links:
      - zookeeper
